apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
        eti: vffffgffvdg
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
          name: guestbook-ui-test
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /healthz # Update to a non-existent path or endpoint
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz # Update to a non-existent path or endpoint
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 5
